on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.ref || github.event.number }}

permissions: {}

jobs:
  pkg-pr-new:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-pkg-pr-new
    if: github.repository == 'fabon-f/temporal-polyfill-lite' && (github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'cr-ready'))
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Publish
        run: pnpm dlx pkg-pr-new@0.0.65 publish --pnpm
